### ISSUE TITLE
Text plist files with values beginning with / are not properly parsed

### ISSUE THREAD

**Issue by cwimberger** [DHowett/go-plist#12]
We have a xcode project file where a key value pair looks like this: "shellPath = /bin/sh;".
When writing back the plist file, the key value pair becomes "shellPath = in/sh;".

I suspect there is a bug in the chugWhitespace function in the text.go file.

**Comment by cwimberger** [comment]
I've created an unit test for the case. Seems like the chugWhitespace function would need a lookahead of 2, but UnreadByte() can only be called once.

```
func TestTextNoCommentDecode(t *testing.T) {
	var testData = "{A=/text;}"
	type D struct{ A string }
	actual := D{"/text"}
	var parsed D
	buf := bytes.NewReader([]byte(testData))
	decoder := NewDecoder(buf)
	err := decoder.Decode(&parsed)
	if err != nil {
		t.Error(err.Error())
	}

	if actual != parsed {
		t.Logf("Expected: %#v", actual)
		t.Logf("Received: %#v", parsed)
		t.Fail()
	}
}
```

**Comment by DHowett** [comment]
Great catch!
