### ISSUE TITLE
Add Marshaller/Unmarshaller interface for working with custom types.

### ISSUE THREAD

**Issue by groob** [DHowett/go-plist#13]
Please add a interface similar to UnmarshallJSON and MarshallJSON. An interface would lend itself better to work with custom types. 
See this talk on JSON for usage: http://talks.golang.org/2015/json.slide#1
To give you a more concrete example, I would like to be able to do the following:

``` go
type Password string `plist:"pass"`

func(p *Password) MarshallPlist() ([]byte, error) {
// do something here
return 
}
```

**Comment by nhelke** [comment]
Would the work I have done in #11 suit you @groob ?

**Comment by DHowett** [comment]
@sapieneptus @groob @nhelke 

The model I think I'm going to go with is to expose `plist.Value`, an interface representing any plist-codable type, as well as the `Marshaler` and `Unmarshaler` types.

`plist.Marshaler.MarshalPlist` should have the signature `MarshalPlist (plist.Value, error)`, and any non-error value returned will be coded in that element's place in the property list.

`plist.Unmarshaler.UnmarshalPlist` is up in the air. I can't tell whether I like go-yaml's `UnmarshalYAML`; it takes a single parameter, a closure that will unmarshal from the current state into a given `interface{}` and returns an error, and returns an error. It's a fair idea.

It could also simply pass a `plist.Value` for the node the `Unmarshaler` represents.

This should give go-plist a sane object model (where every plist-codable object is representable via a publicly-communicable type) without impacting legacy/interface/fielded-struct un/marshalling.

Thoughts?

**Comment by nhelke** [comment]
I assume this new public `plist.Value` will have Marshal` and `Unmarshal` methods? Or functions which can go to and from `plist.Value` to `interface{}` using the existing mechanisms including tags. This would be a boon in custom marshalers/unmarshalers.

I would I would keep it simple and go with `UnmarshalPlist(plist.Value) error`. Also prefer this because of the symmetry with the MarshalPlist signature.
