### ISSUE TITLE
howett.net serves an invalid cert.

### ISSUE THREAD

**Issue by abourget** [DHowett/go-plist#16]
With Go 1.5, I get:

```
$ go get howett.net/plist
package howett.net/plist: unrecognized import path "howett.net/plist"
```

and running `go get` with `-v` shows that there is an invalid cert served at `howett.net`.

The only solution is to `go get -insecure` but this is not done by many automated tools.. so it really blocks automatic acquisition of the package. Can this be fixed ? :)

thanks!

**Comment by IUSR** [comment]
Same issue here with go 1.5.1. A workaround could be to import the github repo path instead, though.

**Comment by sbdchd** [comment]
Although the issue still persists, the following solution worked for me.
```
go get github.com/DHowett/go-plist
```

```
import plist "github.com/DHowett/go-plist"
```

**Comment by djui** [comment]
Please update the README.

**Comment by shurcooL** [comment]
I can reproduce with Go 1.7 right now:

```bash
$ go get howett.net/plist
package howett.net/plist: unrecognized import path "howett.net/plist" (https fetch: Get https://howett.net/plist?go-get=1: x509: certificate is valid for ultraviolet.howett.net, not howett.net)
```

**Comment by DHowett** [comment]
I am very sad about this. I'm going to look at further remediation steps such as serving a legitimate certificate from howett.net.

I'd prefer to have "canonical" import paths for my packages that root them to my web presence, but we all know how well that works. 🤕

**Comment by DHowett** [comment]
howett.net should no longer serve an invalid cert. The canonical import path will remain `howett.net/plist`.
