### ISSUE TITLE
How to handle unknown types?

### ISSUE THREAD

**Issue by sapieneptus** [DHowett/go-plist#17]
Apple's Provisioning Profile plists sometimes contain variable types. E.g., `AssociatedDomains` for an app are sometimes Arrays and sometimes Strings. So if we have an interface:

```
type Profile struct {
 AssociatedDomains []string `plist:com.apple.associated.domains`
}
```

We will get an error if we try to decode this and the AssociatedDomains are a string. 

Is there some way to handle this case?

**Comment by DHowett** [comment]
There's an open pull request #13 implementing custom unmarshalling. I haven't had a chance to look over it, but I do want to get it merged in at some point. You could give it a try!

**Comment by DHowett** [comment]
Duplicate of #13.
