### ISSUE TITLE
parse bplist file result is error

### ISSUE THREAD

**Issue by SuperGod** [DHowett/go-plist#20]
The plist file is a binary plist file, it's struct is like this:

test.plist:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>$archiver</key>
    <string>NSKeyedArchiver</string>
    <key>$top</key>
    <dict>
        <key>ViewController2</key>
        <dict>
            <key>CF$UID</key>
            <integer>1</integer>
        </dict>
    </dict>
    <key>$version</key>
    <integer>100000</integer>
</dict>
</plist>

```

and I use this code to parse it:

```
package main

import (
    "encoding/json"
    "fmt"
    "os"

    "github.com/DHowett/go-plist"
)

func main() {
    f, err := os.Open(`test.plist`)
    if err != nil {
        fmt.Println("error:", err.Error())
        return
    }
    d := plist.NewDecoder(f)
    datas := make(map[string]interface{})
    err = d.Decode(datas)
    if err != nil {
        fmt.Println("error:", err.Error())
        return
    }
    buf, _ := json.Marshal(datas)
    fmt.Println("data:", string(buf))
}
```

but the output is this:

```
data: {"$archiver":"NSKeyedArchiver","$top":{"ViewController2":1},"$version":100000}
```

**Comment by shurcooL** [comment]
> The plist file is a binary plist file, it's struct is like this

It would probably be helpful to attach that binary plist list file to make this issue easier to reproduce.

**Comment by DHowett** [comment]
This is an artifact of how Apple stores UID types. UIDs are just numbers,
but they're indexes into keyed archives like the one you're looking at. In
the bplist format, they've allocated a new tag type (0x80) for them;
however, in the XML format, they haven't. The same UID that a bplist stores
natively is represented as a dictionary containing CF$UID in XML.

go-plist attempts to be cognizant of that and treats that like a UID
(instead of a dictionary), as that is what was intended by Apple.

**Comment by SuperGod** [comment]
@DHowett , so how can I know that a value is an integer or CF$UID?

**Comment by DHowett** [comment]
That's a good question, and one I'm open to suggestions on. I'm considering a `plist.UID` type that can unmarshal into an integral struct field. I don't want to spring surprising types on `map[string]interface{}` consumers, however.

Before we go any further, though, is that what this report is really about? I'd hate to take it down the wrong path.

**Comment by SuperGod** [comment]
I think maybe  the same results of the xml and bin plist  with same struct is good

**Comment by DHowett** [comment]
Full support for UIDs was added recently; if that's not ideal, please reopen this issue.

XML and Binary property lists will now serialize/deserialize UIDs properly under the covers; for XML that is as a dictionary containing `CF$UID`.

You will get a `plist.UID` (typedef for `uint64`), and it can be unmarshaled into an int64/uint64/other integral type, assuming it fits.
