### ISSUE TITLE
add flag to flatten a single-value array

### ISSUE THREAD

**Issue by alaska** [DHowett/go-plist#21]
I'm currently using this library to create plists for launchd.  In a couple of locations, the specification says `<dictionary [of something] or array of dictionaries [of the same thing]>`.  I can't imagine launchd is the only place to do this.  It would be nice to be able to have a flag `flattensingle` such that, given

``` go
type Foo map[string]string

type Dict struct {
    Bar []Foo `plist:",omitempty,flattensingle"`
}

func main() {
    d := Dict{
        Bar: []Foo{
            Foo{
                "name": "one",
                "num":  "two",
            },
        },
    }

    o, e := plist.MarshalIndent(d, plist.XMLFormat, "    ")
    fmt.Println(e)
    fmt.Println(string(o))
}
```

The output would be

``` xml
<plist version="1.0">
    <dict>
        <key>Bar</key>
        <dict>
            <key>name</key>
            <string>one</string>
            <key>num</key>
            <string>two</string>
        </dict>
    </dict>
</plist>

```

Rather than what it is now:

``` xml
<plist version="1.0">
    <dict>
        <key>Bar</key>
        <array>
            <dict>
                <key>name</key>
                <string>one</string>
                <key>num</key>
                <string>two</string>
            </dict>
        </array>
    </dict>
</plist>
```

**Comment by DHowett** [comment]
That's a cool feature. :+1:!

I do, however, have to ask: Will launchd be upset if it gets a
single-element array?

**Comment by alaska** [comment]
A great question, and one I intend to test shortly. If it does, that's your use-case right there.  If not, this could still be useful, but could also be backlogged.

**Comment by DHowett** [comment]
@alaska Did you ever test how launchd reacts to this situation? I'm looking at working on plist package improvements, and I'd like to prioritize my open issues. :smile:

**Comment by alaska** [comment]
I haven't had the time to dig into this.  I'll try and break some time off this weekend.

**Comment by DHowett** [comment]
The changes in 221fc98 should address this. I added an example (well, a test case) for an array that is serialized as a single object or an array depending on how long it is.

**Comment by DHowett** [comment]
That example is [here](https://github.com/DHowett/go-plist/blob/221fc98d0abb603ac75d71b08f60a506751d8665/common_data_for_test.go#L81).
