### ISSUE TITLE
Disappearing commits?

### ISSUE THREAD

**Issue by KenjiTakahashi** [DHowett/go-plist#24]
It seems that my changes from #19 went into abyss.

You're not `--force` pushing to master, are you :-)?

**Comment by DHowett** [comment]
No known force pushes from me! Ugh, sorry.
I do have a mirror with git.howett.net; perhaps that is broken.

**Comment by DHowett** [comment]
@KenjiTakahashi Terribly sorry about that. It does look like the gitolite mirror stomps commits.

I reintroduced your patch and tests with 445e867a489c0469c517d26865e88c4a17e9b4b4.

I hope nothing else got sucked into the abyss with it. Would you mind checking your git history?

☹️

**Comment by KenjiTakahashi** [comment]
Looks fine on my side now, cheers.
