### ISSUE TITLE
Do you have a tutorial or an example?

### ISSUE THREAD

**Issue by xdeng** [DHowett/go-plist#29]
Do you have a tutorial or an example?   I did not find the link

**Comment by shurcooL** [comment]
There is a simple use example in the [README](https://github.com/DHowett/go-plist/blob/master/README.md).

There are also 5 examples in [godoc](https://godoc.org/howett.net/plist#pkg-examples).

**Comment by xdeng** [comment]
@shurcooL Thank you

**Comment by DHowett** [comment]
@shurcooL thank you.

@xdeng I'll close this out since it looks like you've been helped. Feel free to reopen it if you need more assistance!
