### ISSUE TITLE
Canonical howett.net/plist package is not "go gettable"

### ISSUE THREAD

**Issue by lsegal** [DHowett/go-plist#33]
I am running into an issue with `dep ensure` in which [dep](http://github.com/golang/dep) expects the `howett.net/plist` package to be ["go gettable"](https://github.com/golang/dep/issues/1267), in other words, that it follows the same ["Remote import paths" lookup rules](https://golang.org/cmd/go/#hdr-Remote_import_paths) expected by `go get`. It turns out this package is not following these rules properly.

The end result is that `dep ensure` returns the following error:

```
$ dep ensure
...
✗ unable to deduce repository and source type for "howett.net/plist": unable to read metadata: go-import metadata not found
```

Which is a cryptic version of the more understandable error printed by `go get howett.net/plist`:

```
$ go get howett.net/plist
package howett.net/plist: unrecognized import path "howett.net/plist" (parse https://howett.net/plist?go-get=1: no go-import meta tags ())
```

Unfortunately this means I can't use `howett.net/plist` as my canonical import with dep right now, since dep currently does not support custom package names in its constraint solver; a detailed discussion can be found at https://github.com/golang/dep/issues/1267 but tl;dr, it doesn't seem like dep plans on supporting packages that are not "go gettable".

Fortunately this is fairly easily resolved by adding a `/plist` URI to howett.net that responds with something (HTML?) containing:

```
<meta name="go-import" content="howett.net/plist git https://github.com/DHowett/go-plist">
```

I'm not sure if that used to be there and disappeared or if dep changed its behavior, but could this be added (back?) to your domain?

The only other option I have is to move over to `github.com/DHowett/go-plist`, but I read in #22 that you explicitly do not want that name to be used.

**Comment by DHowett** [comment]
This should now be fixed. The _letsencrypt_ installer disabled the `go get` redirect on howett.net.

Thanks for the report!

**Comment by DHowett** [comment]
(and now that I'm home: fix confirmed through _dep_)

**Comment by lsegal** [comment]
Thanks for the quick fix!
