### ISSUE TITLE
Nested array - CustomURL - CFBundleURLSchemes

### ISSUE THREAD

**Issue by Massad** [DHowett/go-plist#45]
Unable to reach to the custom URL values as seen below.

<img width="866" alt="Screen Shot 2019-08-15 at 10 14 40 PM" src="https://user-images.githubusercontent.com/3076722/63165917-d45e5200-c03d-11e9-9811-5961820042f4.png">

Is there any way to capture them? I've reached to this result: `[{[myapp myapp2]}]` but i'll need to strip it and it's not efficient.

```
type CFBundleURLTypes struct {
	URLS []string `plist:"CFBundleURLSchemes"`
}

type iosPlist struct {
	CFBundleName         string             `plist:"CFBundleName"`
	CFBundleDisplayName  string             `plist:"CFBundleDisplayName"`
	CFBundleVersion      string             `plist:"CFBundleVersion"`
	CFBundleShortVersion string             `plist:"CFBundleShortVersionString"`
	CFBundleIdentifier   string             `plist:"CFBundleIdentifier"`
	CFBundleURLSchemes   []CFBundleURLTypes `plist:"CFBundleURLTypes"`
}
```

**Comment by DHowett** [comment]
(did you close this because you solved it, or because it wasn't responded to? this seems like it should work, so should be a valuable bug to track.)
