### ISSUE TITLE
Missing support for GNUstep <[ base64data ]>

### ISSUE THREAD

**Issue by Artoria2e5** [DHowett/go-plist#50]
GNUstep plists have a more efficient data encoding, and it is the `<[ base64data ]>` format:

GNUstep source that emits the format:
https://github.com/gnustep/libs-base/blob/753c907938c2a8c4d00cf0fbe01b7e0d020f0064/Source/NSPropertyList.m#L1951-L1956

GNUstep source that parses the format:
https://github.com/gnustep/libs-base/blob/753c907938c2a8c4d00cf0fbe01b7e0d020f0064/Source/NSPropertyList.m#L1202-L1277

(I wish there is a newer documentation page for the GNUstep format, but I have been unable to locate it.)

**Comment by DHowett** [comment]
Thanks again. I forgot to mark this one closed when #51 merged.
