### ISSUE TITLE
OpenStepFormat parsing can't handle escaped quotations

### ISSUE THREAD

**Issue by catilac** [DHowett/go-plist#56]
` OPXBrowserSignature = "designated => identifier \\"com.apple.Safari\\" and anchor apple\\n";`
As soon as it parses the escaped quotation, it incorrectly looks for a semicolon.
I'm going to try and get a PR up for this in the next couple days.

**Comment by DHowett** [comment]
I'm sorry, I'm not sure I understand. 😄 

Those quotes _aren't escaped_, because the backslashes _are_. Is this well-formed?

**Comment by catilac** [comment]
Ah! You're right. My mistake 😅
This data is from a call to 'defaults read' on macOS. I expected it not to allow for malformed data. I'll look into that!
