### ISSUE TITLE
gitlab.howett.net down?

### ISSUE THREAD

**Issue by bhuvanvenkat-plivo** [DHowett/go-plist#58]
Looks like the site is down and go get is failing.
Error:

```
go: howett.net/plist@v0.0.0-20181124034731-591f970eefbb: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
fatal: unable to access 'https://gitlab.howett.net/go/plist.git/': Failed to connect to gitlab.howett.net port 443: Connection timed out
```
@DHowett Can you please help me out here?

**Comment by DHowett** [comment]
Thanks. I've kicked the VM. Next update in ~10 minutes.

**Comment by DHowett** [comment]
CC @manish-plivo, who reported this in #38.

**Comment by DHowett** [comment]
I've changed the `howett.net` go get redirector to point to this repo. `go get howett.net/plist` now works on my end. Mind giving it another try?

**Comment by bhuvanvenkat-plivo** [comment]
@DHowett Works now!

```
go get howett.net/plist
go: finding howett.net/plist latest
go: downloading howett.net/plist v0.0.0-20200419221736-3b63eb3a43b5
go: extracting howett.net/plist v0.0.0-20200419221736-3b63eb3a43b5
```

**Comment by bhuvanvenkat-plivo** [comment]
@DHowett Thanks for the quick help!

**Comment by DHowett** [comment]
Thanks for the report. Really sorry about that. You all are faster than my server alerting :smile: which is something I should fix.
