### ISSUE TITLE
Error: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by ihbing** [DHowett/go-plist#59]
# the test code
https://github.com/DHowett/go-plist/blob/3b63eb3a43b59c776909681ed1fcb412b47d3c9a/decode_test.go#L178
# result
![QQ截图20200922160822](https://user-images.githubusercontent.com/27600008/93858131-4055c400-fcee-11ea-8d80-522a6c751a9c.png)

**Comment by DHowett** [comment]
Thank you!

This is on purpose. The `TestFormatDetection` test determines whether `plist` can _detect the format_, not whether it can unmarshal the object tree.

The test is passing because the detected formats are correct, but it is printing an error because it tries to unmarshal the object tree.
