### ISSUE TITLE
how to define nested structure

### ISSUE THREAD

**Issue by SolskGaer** [DHowett/go-plist#62]
I got a nested structure that formed like `<dict><dict><array><dict></dict></array></dict></dict>`, and I can't get the innermost dict parsed appropriately, how do I define the struct while parsing this structure?

**Comment by DHowett** [comment]
Since you closed the issue, I'm guessing you figured it out?

**Comment by MarSoft** [comment]
It should be something like this (remember to add `plist:"keyname"` annotations if required).
```
type MyStruct struct{
    KeyName struct{
        SomeArray []struct{
            InnerDictField string
            ...
        }
    }
}
```
