### ISSUE TITLE
Module naming in go.mod uses the module "howett.net/plist" instead of "github.com/DHowett/go-plist"

### ISSUE THREAD

**Issue by pwinkler** [DHowett/go-plist#67]
Summary:
The go.mod defines the module name as "howett.net/plist".  The code is hosted and viewable at github.com/DHowett/go-plist , but a "go get" from the Github address will not work due to the discrepancy.  

The readme _does_ say to use the personal website instead of Github.com, but this is somewhat of a security issue:  It would be easy to have a completely different codebase on howett.net, due to a compromise or other issue.  It would take very conscientious users to make sure that the code gotten from that address always matches the expected code from Github.

Expected behavior:
Code available on Github is usable from Github.

Observed behavior:
The code is available, but not usable, from Github.  In order to use the module, it must be gotten from a 3rd site.

**Comment by DHowett** [comment]
Sorry, I don’t mean to leave you on read. I’m working on an appropriate response to this, as well as some more documentation, but work has been busy. ETA within 7 days hopefully. :)
