### ISSUE TITLE
strong typing of dictionaries

### ISSUE THREAD

**Issue by gedw99** [DHowett/go-plist#69]
I assume all possible plist elements are published somewhere by apple 

if so then it would be possible to generate a parser/ inspector for correctness

this would also allow constructing plist files programmatically that are strongly typed and also I take any third party plist and parse it for correctness.

Is this interesting / worthy for go-plist ?

Does apple publish the plist dictionaries sonewhere ?

**Comment by gedw99** [comment]
Found the key names per Darwin OS here: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html


Unless they have a better source like xml I will have to see rape Thieß pages and sub pages to build a JSON or yaml  file that’s  can be the basis for the plist functionality of parsing for correctness, etc 

the main use is the generate pliers from know constants

**Comment by DHowett** [comment]
@gedw99 thanks for filing this! I'm not totally sure what you're asking for, unfortunately. This library supports parsing a plist into fully type-specified storage.

Reading between the lines, though... are you looking for a tool or specification document that will allow you to produce a type description of an existing property list document?

Something like that could be done with type assertions over a `map[string]interface{}` that you populate using this library, but there's no out-of-the-box support for making that.

Unfortunately, the property list schema only documents what a property list _is_... and there is no existing schema documentation for different types of plist documents. There's no source that will help you figure out what any given document should contain. ☹️

**Comment by gedw99** [comment]
Hey @DHowett 

Sorry i wrote the original issue from a mobile and realised how my spelling screwed it up.

So basically in the GIOUI project you can target Web, Desktop and Mobile ( and Apple TV ), and so i am working on a way for each golang package to be able to add to the Packaging Manifest ( Plist for Apple hardware), and so easily build correct manifest.

Then i had the idea that we also built golang strongly typed PList constants by scraping the Apple web site for then, and generating the Constant with nice Comments.

The Golang packages can then use the constants to build a Manifest.

Plus as a bonus we can parse a Manifest and check the Dictionary keys ( as Apple calls them ) are correct.

Does this make more sense now ???

**Comment by gedw99** [comment]
I also intend to do the same for Android and Web Manifests.

**Comment by DHowett** [comment]
> Does this make more sense now ???

It absolutely does make sense! I think that having a separate package containing Apple types, annotated with `plist:` struct tags, would be an excellent idea.

I also don't think that it is in the critical path for this package. Right now, we're just a generic data codec for the wire format of Apple Property Lists. Types other than `UID` (which is an intrinsic plist type) should be provided by other packages.

Thanks for explaining!
