### ISSUE TITLE
How to handle plists with keys with commas?

### ISSUE THREAD

**Issue by blacktop** [DHowett/go-plist#70]
For example:

```xml
			<key>SE,ChipID</key>
			<string>0x73</string>
			<key>Savage,ChipID</key>
			<string>0x01</string>
			<key>Savage,PatchEpoch</key>
			<string>0x00</string>
```

**Comment by DHowett** [comment]
That's an excellent question. I thought that you'd be able to specify keys containing commas by setting tags on struct fields (ala `plist:"SE,ChipID"`), but it looks like the key parser isn't up to the task.

In the meantime, you may want to unmarshal into a `map[string]interface{}` and pull the data out directly.

**Comment by DHowett** [comment]
It looks like `encoding/json` doesn't have any prior art for this. I'm gonna follow their lead and close this out, but with the continued recommendation to use `map[string]interface{}`.
