### ISSUE TITLE
Question: flatten property

### ISSUE THREAD

**Issue by al3xandru** [DHowett/go-plist#71]
Is there a way to flatten the structure when unmarshalling?

Example: given

```xml
<dict>
<key>URIDictionary</key>
    <dict>
        <key>title</key>
        <string>Inspection and the limits of trust.</string>
    </dict>
    ...
</dict>
```

would it be possible to read the `title` key directly without creating a new `struct` for `URIDictionary`?

thank you

**Comment by DHowett** [comment]
Unfortunately, this isn't something we support today and it is not on the roadmap. I'm sorry.
