### ISSUE TITLE
plist.Marshal("aaa", plist.BinaryFormat) is not return the expected value

### ISSUE THREAD

**Issue by stephane-archer** [DHowett/go-plist#81]
Hi, I'm trying to encode a string to a binary Plist but I don't find the expected result.
How can I make Plist return the right result?

For example the string `"Iphone 11 Pro"` gets transformed with your package in `"bplist00^Iphone 11 Pro"` but I expect to get `"bplist00]iPhone 11 Pro"`.
I'm not sure what the `"]"` and `"^"` characters represent.

Also the string `"aaa"` gets transformed with your package in `"bplist00Taaa"` but I expect to get `"bplist00Saaa"`.
once again I'm not sure what `"S"` and `"T"` represent

**Comment by stephane-archer** [comment]
Thank you for your answer. 
These letters make more sense to me now thanks to you and hexadecimal 

I was adding "Finder tags" using "Mac Finder" then I was using "xattr -l" to see the value added and tried to "reverse engineer" what was going on
But adding the same value returned by "xattr -l" is not adding the tag so it doesn't seem to be a reliable tool.

At the end of your answer, I can see a lot of data after the "aaa" What is it?

**Comment by DHowett** [comment]
The data after the `aaa` is the binary plist "trailer," which is a binary format that specifies the layout of the objects inside the property list!
